stateDiagram
  state Vue {
    VueRouter
    VueStore
    VueI18n
  }
  state Data {
    Title
    CustomAdminRoutes
    Locales
    Translations
    Resources
  }
  state Providers {
    AuthProvider
    DataProvider
  }
  Vue --> VuetifyAdmin
  Data --> VuetifyAdmin
  Providers --> VuetifyAdmin
  VuetifyAdmin --> CRUDRoutes: Build
  VuetifyAdmin --> ResourceModules: Build
