stateDiagram
  state Architecture {
    state VtecAdmin {
      Layout
      Fields
      Inputs
    }
    Vuetify --> VtecAdmin: Components
    Vuetify --> UserCodeLand: Components
    VtecAdmin --> UserCodeLand: Components
    state UserCodeLand {
      Resources --> VueRouter: VABuilder
      Resources --> Vuex: VABuilder
      state VueRouter {
        List
        Show
        Create
        Edit
      }
      state Vuex {
        AuthProvider
        DataProvider
      }
      VueRouter --> Vuex: Dispatch
    }
    UserCodeLand --> Server: HTTP Rest calls
    state Server {
      API
    }
  }
