stateDiagram
  state GenerationProcess {
  [*] --> YAML
  YAML --> GeneratorCommands
  state GeneratorCommands {
    CrudYaml --> CrudMake
  }
  GeneratorCommands --> Templates
  GeneratorCommands --> Register
  state Templates {
    List,Show,Create,Edit,Form
  }
  state Register {
    Resources,Locales,Nav
  }
}
